INSERT INTO agents(agentID,IPaddr,os,service,team) values ("OZVXJU", INET_ATON("10.1.2.2"),"Ubuntu","Web","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("1ZYTYM", INET_ATON("10.1.2.3"),"CentOS","Database","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("L18DH9", INET_ATON("10.1.2.4"),"Windows Server 2016","FTP","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("AI7527", INET_ATON("10.1.2.10"),"Ubuntu","IoT","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GPG94L", INET_ATON("10.1.2.12"),"NA","CalDev","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NO45D4", INET_ATON("10.1.2.14"),"Ubuntu","HTTP/SSH","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("I45PNR", INET_ATON("10.1.1.10"),"NA","ICMP/SSH","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SJXRK3", INET_ATON("10.1.1.40"),"Ubuntu","SSH","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("MK2M3Y", INET_ATON("10.1.1.60"),"Windows Server 2019","LDAP/DNS","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("9987DU", INET_ATON("10.1.1.70"),"Windows 10","WinRM","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("1JDR78", INET_ATON("10.1.1.80"),"Windows 10","WinRM","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("X9BPK3", INET_ATON("10.1.1.90"),"Windows 10","WinRM","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("TX12CR", INET_ATON("10.1.1.100"),"Windows 10","WinRM","1");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("8GP7X8", INET_ATON("10.2.2.2"),"Ubuntu","Web","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NAS4KN", INET_ATON("10.2.2.3"),"CentOS","Database","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("3Y0LI4", INET_ATON("10.2.2.4"),"Windows Server 2016","FTP","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("OIVCQ6", INET_ATON("10.2.2.10"),"Ubuntu","IoT","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("HIVL05", INET_ATON("10.2.2.12"),"NA","CalDev","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("2P5UGY", INET_ATON("10.2.2.14"),"Ubuntu","HTTP/SSH","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("FOK6DA", INET_ATON("10.2.1.10"),"NA","ICMP/SSH","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SWYNZ7", INET_ATON("10.2.1.40"),"Ubuntu","SSH","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ABKH11", INET_ATON("10.2.1.60"),"Windows Server 2019","LDAP/DNS","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RRZ0VN", INET_ATON("10.2.1.70"),"Windows 10","WinRM","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("5QEOEQ", INET_ATON("10.2.1.80"),"Windows 10","WinRM","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("Y39CTV", INET_ATON("10.2.1.90"),"Windows 10","WinRM","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("87Z6LW", INET_ATON("10.2.1.100"),"Windows 10","WinRM","2");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("BQWEWV", INET_ATON("10.3.2.2"),"Ubuntu","Web","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RIC6L8", INET_ATON("10.3.2.3"),"CentOS","Database","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("MLYMBR", INET_ATON("10.3.2.4"),"Windows Server 2016","FTP","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("11JN8Q", INET_ATON("10.3.2.10"),"Ubuntu","IoT","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("I23957", INET_ATON("10.3.2.12"),"NA","CalDev","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("R40EGH", INET_ATON("10.3.2.14"),"Ubuntu","HTTP/SSH","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("W5FX8M", INET_ATON("10.3.1.10"),"NA","ICMP/SSH","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6MFK84", INET_ATON("10.3.1.40"),"Ubuntu","SSH","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("TT1V0Z", INET_ATON("10.3.1.60"),"Windows Server 2019","LDAP/DNS","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("H6C9BV", INET_ATON("10.3.1.70"),"Windows 10","WinRM","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("B2WLXO", INET_ATON("10.3.1.80"),"Windows 10","WinRM","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("X2MPYO", INET_ATON("10.3.1.90"),"Windows 10","WinRM","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("T84330", INET_ATON("10.3.1.100"),"Windows 10","WinRM","3");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SHWCNJ", INET_ATON("10.4.2.2"),"Ubuntu","Web","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("QTPZD3", INET_ATON("10.4.2.3"),"CentOS","Database","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("3D8SQ7", INET_ATON("10.4.2.4"),"Windows Server 2016","FTP","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("XF7QIJ", INET_ATON("10.4.2.10"),"Ubuntu","IoT","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("C6V8OI", INET_ATON("10.4.2.12"),"NA","CalDev","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("K1T2Y5", INET_ATON("10.4.2.14"),"Ubuntu","HTTP/SSH","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SOR6BL", INET_ATON("10.4.1.10"),"NA","ICMP/SSH","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RJZZXI", INET_ATON("10.4.1.40"),"Ubuntu","SSH","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("F2F4CU", INET_ATON("10.4.1.60"),"Windows Server 2019","LDAP/DNS","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("06S28R", INET_ATON("10.4.1.70"),"Windows 10","WinRM","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SV5ZG4", INET_ATON("10.4.1.80"),"Windows 10","WinRM","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("OK9EBM", INET_ATON("10.4.1.90"),"Windows 10","WinRM","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("YA4O6I", INET_ATON("10.4.1.100"),"Windows 10","WinRM","4");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ACSLOT", INET_ATON("10.5.2.2"),"Ubuntu","Web","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6MWUJE", INET_ATON("10.5.2.3"),"CentOS","Database","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("R5D28N", INET_ATON("10.5.2.4"),"Windows Server 2016","FTP","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("U3M22Z", INET_ATON("10.5.2.10"),"Ubuntu","IoT","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("K2G9PO", INET_ATON("10.5.2.12"),"NA","CalDev","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GOD7VY", INET_ATON("10.5.2.14"),"Ubuntu","HTTP/SSH","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("JW4G13", INET_ATON("10.5.1.10"),"NA","ICMP/SSH","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("HD1553", INET_ATON("10.5.1.40"),"Ubuntu","SSH","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("I3TJNN", INET_ATON("10.5.1.60"),"Windows Server 2019","LDAP/DNS","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("0007GB", INET_ATON("10.5.1.70"),"Windows 10","WinRM","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("FJF63A", INET_ATON("10.5.1.80"),"Windows 10","WinRM","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("A42WDH", INET_ATON("10.5.1.90"),"Windows 10","WinRM","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("VSK25Q", INET_ATON("10.5.1.100"),"Windows 10","WinRM","5");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("7FTMOH", INET_ATON("10.6.2.2"),"Ubuntu","Web","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("MZDR46", INET_ATON("10.6.2.3"),"CentOS","Database","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("H57YLN", INET_ATON("10.6.2.4"),"Windows Server 2016","FTP","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("V65RMH", INET_ATON("10.6.2.10"),"Ubuntu","IoT","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("PJ8SBC", INET_ATON("10.6.2.12"),"NA","CalDev","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GI1VNZ", INET_ATON("10.6.2.14"),"Ubuntu","HTTP/SSH","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RIO1GA", INET_ATON("10.6.1.10"),"NA","ICMP/SSH","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6VX2RT", INET_ATON("10.6.1.40"),"Ubuntu","SSH","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("YQ12NO", INET_ATON("10.6.1.60"),"Windows Server 2019","LDAP/DNS","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DM4WVF", INET_ATON("10.6.1.70"),"Windows 10","WinRM","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ZNYPO0", INET_ATON("10.6.1.80"),"Windows 10","WinRM","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RO6YTU", INET_ATON("10.6.1.90"),"Windows 10","WinRM","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("R4AV3J", INET_ATON("10.6.1.100"),"Windows 10","WinRM","6");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("CMRHW2", INET_ATON("10.7.2.2"),"Ubuntu","Web","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("FDG5Q1", INET_ATON("10.7.2.3"),"CentOS","Database","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GMXMTG", INET_ATON("10.7.2.4"),"Windows Server 2016","FTP","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("0A9585", INET_ATON("10.7.2.10"),"Ubuntu","IoT","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("T6YJYC", INET_ATON("10.7.2.12"),"NA","CalDev","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NR4H38", INET_ATON("10.7.2.14"),"Ubuntu","HTTP/SSH","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("LLV4UJ", INET_ATON("10.7.1.10"),"NA","ICMP/SSH","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("MSWYKS", INET_ATON("10.7.1.40"),"Ubuntu","SSH","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("P25TUV", INET_ATON("10.7.1.60"),"Windows Server 2019","LDAP/DNS","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("1GLK1K", INET_ATON("10.7.1.70"),"Windows 10","WinRM","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("AE4TXM", INET_ATON("10.7.1.80"),"Windows 10","WinRM","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("H1UZVK", INET_ATON("10.7.1.90"),"Windows 10","WinRM","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("PSFNGP", INET_ATON("10.7.1.100"),"Windows 10","WinRM","7");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("KC1CZ5", INET_ATON("10.8.2.2"),"Ubuntu","Web","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("F1C3EE", INET_ATON("10.8.2.3"),"CentOS","Database","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("N3GMD0", INET_ATON("10.8.2.4"),"Windows Server 2016","FTP","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SGXILI", INET_ATON("10.8.2.10"),"Ubuntu","IoT","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("06KC0I", INET_ATON("10.8.2.12"),"NA","CalDev","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("JELB7J", INET_ATON("10.8.2.14"),"Ubuntu","HTTP/SSH","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("CSCCYL", INET_ATON("10.8.1.10"),"NA","ICMP/SSH","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DBTVJA", INET_ATON("10.8.1.40"),"Ubuntu","SSH","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("WF1MV3", INET_ATON("10.8.1.60"),"Windows Server 2019","LDAP/DNS","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("URW6LR", INET_ATON("10.8.1.70"),"Windows 10","WinRM","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("XUEACM", INET_ATON("10.8.1.80"),"Windows 10","WinRM","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("0Q6M7M", INET_ATON("10.8.1.90"),"Windows 10","WinRM","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("FINANI", INET_ATON("10.8.1.100"),"Windows 10","WinRM","8");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DKZ5KW", INET_ATON("10.9.2.2"),"Ubuntu","Web","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("J4FMGU", INET_ATON("10.9.2.3"),"CentOS","Database","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("K2J3Y0", INET_ATON("10.9.2.4"),"Windows Server 2016","FTP","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("L6BJM8", INET_ATON("10.9.2.10"),"Ubuntu","IoT","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("37CBCE", INET_ATON("10.9.2.12"),"NA","CalDev","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("PU74YP", INET_ATON("10.9.2.14"),"Ubuntu","HTTP/SSH","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6QA4AZ", INET_ATON("10.9.1.10"),"NA","ICMP/SSH","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("HGCKH3", INET_ATON("10.9.1.40"),"Ubuntu","SSH","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("2RIQDP", INET_ATON("10.9.1.60"),"Windows Server 2019","LDAP/DNS","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("Y1FLG3", INET_ATON("10.9.1.70"),"Windows 10","WinRM","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GLCFKB", INET_ATON("10.9.1.80"),"Windows 10","WinRM","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("340VPJ", INET_ATON("10.9.1.90"),"Windows 10","WinRM","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("8RKAMA", INET_ATON("10.9.1.100"),"Windows 10","WinRM","9");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("Y1B53R", INET_ATON("10.10.2.2"),"Ubuntu","Web","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("7X269D", INET_ATON("10.10.2.3"),"CentOS","Database","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DX0BS6", INET_ATON("10.10.2.4"),"Windows Server 2016","FTP","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("E6S3BE", INET_ATON("10.10.2.10"),"Ubuntu","IoT","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("QC06H3", INET_ATON("10.10.2.12"),"NA","CalDev","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("EZY3QL", INET_ATON("10.10.2.14"),"Ubuntu","HTTP/SSH","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GEQD0M", INET_ATON("10.10.1.10"),"NA","ICMP/SSH","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("LBS6CK", INET_ATON("10.10.1.40"),"Ubuntu","SSH","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("D6IJ65", INET_ATON("10.10.1.60"),"Windows Server 2019","LDAP/DNS","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ZCDM73", INET_ATON("10.10.1.70"),"Windows 10","WinRM","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("7GLTYN", INET_ATON("10.10.1.80"),"Windows 10","WinRM","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("V2QEJU", INET_ATON("10.10.1.90"),"Windows 10","WinRM","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ZPADUQ", INET_ATON("10.10.1.100"),"Windows 10","WinRM","10");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SFTRW5", INET_ATON("10.11.2.2"),"Ubuntu","Web","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("C57EPK", INET_ATON("10.11.2.3"),"CentOS","Database","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("L93D3P", INET_ATON("10.11.2.4"),"Windows Server 2016","FTP","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("9C7RBG", INET_ATON("10.11.2.10"),"Ubuntu","IoT","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("QBDTUK", INET_ATON("10.11.2.12"),"NA","CalDev","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6UPWAU", INET_ATON("10.11.2.14"),"Ubuntu","HTTP/SSH","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("XPYYQG", INET_ATON("10.11.1.10"),"NA","ICMP/SSH","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("JD6G7K", INET_ATON("10.11.1.40"),"Ubuntu","SSH","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("37H1P4", INET_ATON("10.11.1.60"),"Windows Server 2019","LDAP/DNS","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("QPK3HJ", INET_ATON("10.11.1.70"),"Windows 10","WinRM","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("454AC1", INET_ATON("10.11.1.80"),"Windows 10","WinRM","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("BLPCK2", INET_ATON("10.11.1.90"),"Windows 10","WinRM","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NOLHWM", INET_ATON("10.11.1.100"),"Windows 10","WinRM","11");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("HJTE5R", INET_ATON("10.12.2.2"),"Ubuntu","Web","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("FTQITE", INET_ATON("10.12.2.3"),"CentOS","Database","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("38F1HV", INET_ATON("10.12.2.4"),"Windows Server 2016","FTP","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("3U9L0S", INET_ATON("10.12.2.10"),"Ubuntu","IoT","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NC08ZQ", INET_ATON("10.12.2.12"),"NA","CalDev","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("P7WXIA", INET_ATON("10.12.2.14"),"Ubuntu","HTTP/SSH","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ILJ51J", INET_ATON("10.12.1.10"),"NA","ICMP/SSH","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("9GZK5Y", INET_ATON("10.12.1.40"),"Ubuntu","SSH","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("9YMRDT", INET_ATON("10.12.1.60"),"Windows Server 2019","LDAP/DNS","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("KZ82N9", INET_ATON("10.12.1.70"),"Windows 10","WinRM","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DHJABO", INET_ATON("10.12.1.80"),"Windows 10","WinRM","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("Q2KUTB", INET_ATON("10.12.1.90"),"Windows 10","WinRM","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("C1W2W1", INET_ATON("10.12.1.100"),"Windows 10","WinRM","12");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SY8JW8", INET_ATON("10.13.2.2"),"Ubuntu","Web","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("RVFERE", INET_ATON("10.13.2.3"),"CentOS","Database","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("6Q72W2", INET_ATON("10.13.2.4"),"Windows Server 2016","FTP","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("T52VP1", INET_ATON("10.13.2.10"),"Ubuntu","IoT","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SBZ9GJ", INET_ATON("10.13.2.12"),"NA","CalDev","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("LMZM8O", INET_ATON("10.13.2.14"),"Ubuntu","HTTP/SSH","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("YEDPXT", INET_ATON("10.13.1.10"),"NA","ICMP/SSH","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("T9RSKY", INET_ATON("10.13.1.40"),"Ubuntu","SSH","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("A109UL", INET_ATON("10.13.1.60"),"Windows Server 2019","LDAP/DNS","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("7TUG5S", INET_ATON("10.13.1.70"),"Windows 10","WinRM","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("EIP411", INET_ATON("10.13.1.80"),"Windows 10","WinRM","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("MYPGWP", INET_ATON("10.13.1.90"),"Windows 10","WinRM","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ZTVVC0", INET_ATON("10.13.1.100"),"Windows 10","WinRM","13");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("JVSB4V", INET_ATON("10.14.2.2"),"Ubuntu","Web","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("YTQ8EX", INET_ATON("10.14.2.3"),"CentOS","Database","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("UHSFJ4", INET_ATON("10.14.2.4"),"Windows Server 2016","FTP","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("8MXUC8", INET_ATON("10.14.2.10"),"Ubuntu","IoT","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("XXSJ28", INET_ATON("10.14.2.12"),"NA","CalDev","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DXCV83", INET_ATON("10.14.2.14"),"Ubuntu","HTTP/SSH","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("DJH0RB", INET_ATON("10.14.1.10"),"NA","ICMP/SSH","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("5IPMWB", INET_ATON("10.14.1.40"),"Ubuntu","SSH","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("8O7MDH", INET_ATON("10.14.1.60"),"Windows Server 2019","LDAP/DNS","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("UD7TIE", INET_ATON("10.14.1.70"),"Windows 10","WinRM","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("IR4BBJ", INET_ATON("10.14.1.80"),"Windows 10","WinRM","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("TVC3LT", INET_ATON("10.14.1.90"),"Windows 10","WinRM","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GG69LR", INET_ATON("10.14.1.100"),"Windows 10","WinRM","14");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("AKQS4M", INET_ATON("10.15.2.2"),"Ubuntu","Web","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("54RA3H", INET_ATON("10.15.2.3"),"CentOS","Database","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("5DW048", INET_ATON("10.15.2.4"),"Windows Server 2016","FTP","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("J0ZRB0", INET_ATON("10.15.2.10"),"Ubuntu","IoT","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("GW7BS0", INET_ATON("10.15.2.12"),"NA","CalDev","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("AUEFDM", INET_ATON("10.15.2.14"),"Ubuntu","HTTP/SSH","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("I210AZ", INET_ATON("10.15.1.10"),"NA","ICMP/SSH","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("NC8K6D", INET_ATON("10.15.1.40"),"Ubuntu","SSH","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("JZ9GNO", INET_ATON("10.15.1.60"),"Windows Server 2019","LDAP/DNS","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("UZJUQM", INET_ATON("10.15.1.70"),"Windows 10","WinRM","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("SIO0TS", INET_ATON("10.15.1.80"),"Windows 10","WinRM","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("ERIRCR", INET_ATON("10.15.1.90"),"Windows 10","WinRM","15");
INSERT INTO agents(agentID,IPaddr,os,service,team) values ("B37FML", INET_ATON("10.15.1.100"),"Windows 10","WinRM","15");
